// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Stride.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class DirectionalBlurShaderKeys
    {
        public static readonly ValueParameterKey<float> Angle = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> BlurAmount = ParameterKeys.NewValue<float>(0.005f);
    }
}
